dataset: "cifar10" # Options: mnist, fashion_mnist, cifar10, cifar100

# Dataset configurations
datasets:
  mnist:
    input_size: [1, 28, 28]
    num_classes: 10
    in_channels: 1
  fashion_mnist:
    input_size: [1, 28, 28]
    num_classes: 10
    in_channels: 1
  cifar10:
    input_size: [3, 32, 32]
    num_classes: 10
    in_channels: 3
  cifar100:
    input_size: [3, 32, 32]
    num_classes: 100
    in_channels: 3

model:
  type: "gcnn"
  group_type: "cyclic" # Options: cyclic, dihedral
  group_order: 4 # For cyclic: order of rotation group (C4, C8, etc.)
  kernel_size: 5
  num_hidden: 4
  hidden_channels: 16
  padding: 0
  stride: 1

data:
  # 0.82 for mnist and fashion_mnist
  # 0.84 for cifar10 and cifar100
  train_proportion: 0.82
  random_rotation_train: false
  random_rotation_test: False
  batch_size: 64

training:
  max_epochs: 20
  log_every_n_steps: 50

optimizer:
  type: "adamw"
  learning_rate: 0.001
  weight_decay: 0.0001
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
